import React from 'react';

const AboutPage: React.FC = () => {
  return (
    <div className="bg-slate-800/60 rounded-xl shadow-xl overflow-hidden border border-slate-700/50 backdrop-blur-sm p-6">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-center mb-10">
          <div className="bg-blue-600 w-14 h-14 rounded-xl shadow-lg flex items-center justify-center mr-4 relative overflow-hidden group">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-white z-10 group-hover:scale-110 transition-transform duration-300" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
            </svg>
            <div className="absolute inset-0 bg-gradient-to-tr from-blue-700 to-blue-500 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
          </div>
          <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-blue-400 to-indigo-500">
            About CodeWatch
          </h1>
        </div>
      
        <div className="space-y-6 text-slate-300">
          <p className="text-xl leading-relaxed">
            CodeWatch is an innovative platform designed to help developers understand and analyze code patterns.
            Our mission is to make code analysis more accessible and efficient using AI technology.
          </p>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-10">
            <div className="bg-slate-900/50 p-5 rounded-lg border border-slate-700/50 hover:border-blue-500/30 transition-all group">
              <div className="w-12 h-12 rounded-lg bg-blue-600/20 flex items-center justify-center mb-4 group-hover:bg-blue-600/30 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Smart Detection</h3>
              <p className="text-slate-400">
                Our algorithm analyzes subtle patterns in code to determine whether it was generated by AI or written by humans.
              </p>
            </div>
            
            <div className="bg-slate-900/50 p-5 rounded-lg border border-slate-700/50 hover:border-blue-500/30 transition-all group">
              <div className="w-12 h-12 rounded-lg bg-blue-600/20 flex items-center justify-center mb-4 group-hover:bg-blue-600/30 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Detailed Analytics</h3>
              <p className="text-slate-400">
                Get comprehensive insights into the structural and semantic characteristics that influence the detection results.
              </p>
            </div>
            
            <div className="bg-slate-900/50 p-5 rounded-lg border border-slate-700/50 hover:border-blue-500/30 transition-all group">
              <div className="w-12 h-12 rounded-lg bg-blue-600/20 flex items-center justify-center mb-4 group-hover:bg-blue-600/30 transition-colors">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-blue-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">Multiple Languages</h3>
              <p className="text-slate-400">
                Supporting a wide range of programming languages including JavaScript, Python, Java, and more.
              </p>
            </div>
          </div>
          
          <div className="mt-10 bg-blue-600/10 border border-blue-500/20 rounded-lg p-6">
            <h2 className="text-2xl font-bold text-white mb-4">Our Technology</h2>
            <p className="text-slate-300">
              CodeWatch leverages advanced embedding models and similarity analysis to compare code against known patterns of AI-generated content. Our approach is based on research that shows AI models generate code with distinctive statistical signatures that differ from human code.
            </p>
          </div>
          
          <div className="mt-10 text-center">
            <p className="text-slate-400">
              Have questions or feedback? We'd love to hear from you!
            </p>
            <button className="mt-4 px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-md transition-all duration-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 shadow-md hover:shadow-lg flex items-center mx-auto">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              Contact Us
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AboutPage;